### ISSUE TITLE
AddOn not working in Blender 2.69 to 2.93

### ISSUE THREAD

**Issue by TorstenFunk** [gyoerkaa/nvx2loader#2]
Hello, I tried this add-on in several Blender versions like 2.69, 2.78c, 2.79, 2.80, 2.83 and 2.93, but I don't get it working. 

2.78c might be the closest Blender version to when this add-on was written. It shows the "Nebula mesh (.nvx2)" entry in the Import menu, but after selecting a file and importing it, I get the error message "AttributeError: module 'enum' has no attribute 'IntFlag' ... location <unknown location>:-1". And no mesh was imported at all.

![addon](https://github.com/gyoerkaa/nvx2loader/assets/36140729/35c7732d-1529-4246-8a20-1ec6a2735dfb)

Newer Blender versions like 2.80 and up don't show the "Nebula mesh (.nvx2)" entry in the Import menu.

For which Blender version was this add-on written? Any feedback appreciated.

**Comment by gyoerkaa** [comment]
Hi, I've pushed some fixes, which should make it work again for Blender 2.72 and 2.79 (only versions I tested)

The AddOn was originally made for 2.71, I think. It won't work in 2.8 or later version due to API changes. Didn't think people were still using it, I'll see about updating it to 4.0.

**Comment by gyoerkaa** [comment]
I've released an Update for Blender 4.0. The legacy code for Blender 2.7 has been moved to a separate branch.

**Comment by BaalNetbek** [comment]
Thank you. I was trying to port the plugin to new blender few days ago. I failed but now I see that you did that after 6 years or so. What a coincidence.
